# Comentario
server:
  port: 8080

spring:
  application:
    name: aprende01-clase
  datasource:
    url: jdbc:h2:file:./bd.aprende01
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      #ddl-auto: create
      #ddl-auto=create-drop
      #ddl-auto=none



logging:
  file:
    name: logs/app.log
